server:
  port: ${PORT:8080}

spring:
  application:
    name: accidentdetector


twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  fromNumber: ${TWILIO_FROM_NUMBER}
  toNumber: ${TWILIO_TO_NUMBER}
  appBaseUrl: ${APP_BASE_URL}

