spring:
  application:
    name: accidentdetector
  server:
    port: ${PORT:8081}


twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  fromNumber: ${TWILIO_FROM_NUMBER}
  toNumber: ${TWILIO_TO_NUMBER}

